# Config settings
title: Learn markdown with Search Demo
baseurl: "/learnmarkdown"

# Search settings
tipue_search:
  include:
    pages: true
  exclude:
    files: [index.md, search.html]

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-optional-front-matter
  - jekyll-relative-links
  - jekyll-html-pipeline
exclude:
  - Gemfile
  - Gemfile.lock

header_pages:
  - about.md
  - index.md
  - search.html
  - search1.html
