# Config settings
title: Learn markdown with Search Demo
baseurl: "/learnmarkdown"

# Search settings
tipue_search:
  include:
    pages: true
  exclude:
    files: [index.md, search.html]

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
